import type { Metadata } from "next";
import { Hepta_Slab } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";
import StoreProvider from "../store/storeProvider";
import ToastProvider from "@/providers/ToastProvider";
import GameOverModal from "../components/GameOverModal";


const heptaSlab = Hepta_Slab({ subsets: ["latin"],variable:"--font-hepta-slab",display:"swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props ={
  children: React.ReactNode;
  params:{
    locale: "en"| "tr"
  }
}

const RootLayout: React.FC<Props> =({children, params: { locale }})=> {
  const messages =  useMessages();
  return (
    <html>
      <body lang={locale} suppressHydrationWarning={true} className={`${heptaSlab.variable}`}>

        <NextIntlClientProvider messages={messages}>
          <StoreProvider>
            <ToastProvider>
              {children}
              <GameOverModal/>
            </ToastProvider>
          </StoreProvider>
      </NextIntlClientProvider>
      </body>
    </html>
  );
}

export default RootLayout;